apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: cdps-18
  labels:
    app: reviews
    service: reviews
spec:
  type: ClusterIP
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---