apiVersion: v1
kind: Service
metadata:
  name: details-service
  namespace: cdps-18
  labels:
    app: details
    service: details
spec:
  selector:
    app: details
  ports:
  - port: 9080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-deployment
  namespace: cdps-18
spec:
  replicas: 4
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: yagoferrara/practica_creativa2:details
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---