apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: cdps-18
  labels:
    app: productpage
    service: productpage
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
  - port: 9080
    name: http
    targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
  namespace: cdps-18
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: yagoferrara/practica_creativa2:productpage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---