apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: cdps-18
  labels:
    app: ratings
    service: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 9080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
  namespace: cdps-18
  labels:
    app: ratings
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: yagoferrara/practica_creativa2:ratings
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---